### ISSUE TITLE
Update regexp

### ISSUE THREAD

**Issue by ghost** [marcoms/oceanic-plus#1]
https://code.visualstudio.com/updates/v1_17#_improved-colorization-in-dark-and-light-themes

**Comment by marcoms** [comment]
Looks like this is the relevant portion of the changes -- https://github.com/Microsoft/vscode/commit/845fa13b416abd6ee5cf34c5ffbbfa7bf12d0575#diff-8d3b9ffedf59508bad5ca581a5b9b624R106

I'll take a look hopefully sometime soon

**Comment by marcoms** [comment]
Improved regex coverage in af8ce40eeb548bf5f8212aa4760344fe6f249548
