### ISSUE TITLE
destructuring assignment colors

### ISSUE THREAD

**Issue by DJTB** [marcoms/oceanic-plus#2]
Hi,
Firstly, you've done a really good job on this, much more clarity than any of the other vscode oceanic ports!

I was just curious if you could somehow add a color difference when changing a variable name during destructuring. WIth my atom version of oceanic next I've found it really helpful to see at a glance which variable will be assigned through the expression.

atom:
![image](https://user-images.githubusercontent.com/5353151/35179522-0d16b072-fdf0-11e7-9694-1d6f1f69769b.png)

vscode:
![image](https://user-images.githubusercontent.com/5353151/35179523-1522203a-fdf0-11e7-9e88-6ccdf5188ec9.png)

It may be an accidental coloring, since the green appears to just be the color used for object keys. Though it's useful nonetheless!

atom:
![image](https://user-images.githubusercontent.com/5353151/35179542-676ff812-fdf0-11e7-8e35-6334f08bdff8.png)

vscode:
![image](https://user-images.githubusercontent.com/5353151/35179540-53d797c4-fdf0-11e7-895f-a89b47b6cfd2.png)

**Comment by mikehdt** [comment]
It looks like you might have the plugin `Rainbow Brackets` installed?

**Comment by DJTB** [comment]
That's true, I do - but that is only coloring the `{` `}`.
What I was discussing is the variable destructuring color.
For argument destructuring the final variables are colored.
For object destructuring they are all the same.

Hopefully this is more clear:
![image](https://user-images.githubusercontent.com/5353151/37498475-b3e6d25e-2912-11e8-9de7-d32955b21c1c.png)

It would be great if `newName` and `anotherNewName` were colored orange in the same way that `anArgument` and `anotherArgument` are.

**Comment by mikehdt** [comment]
It looks fine for me, but there's two things I have done differently.

One, is that I added the `Sublime Babel` package -- I find it works better than the other Babel packages for highlighting colours with the new ES2015+ bits and pieces. I suspect this will be the biggest help to better destructuring colours (make sure to remove any other Babel-ish plugins or at least disable them first)

Second, I added this to my preferences:
```
    "editor.tokenColorCustomizations": {
        "[Oceanic Plus]": {
            "variables": "#cdd3de"
        }
    },
```
because I'm _really_ not a fan of having to read so much of that sort of light salmon colour. I find it really fatiguing and hard to look at over a long period, but that's just me though ;) The colour I've added more closely matches the Sublime version of Oceanic Next.

**Comment by DJTB** [comment]
Ah ok, so you're saying this is an issue with vscode's JS syntax tokenizing then - not something that can be amended from within this theme?

If that's the case, feel free to close this issue.

**Comment by mikehdt** [comment]
No, but if you install the `Sublime Babel` add-on for VS Code, you may be a lot happier I think 😉 

I'm just another user, so I'd leave it up to you to close the issue, I don't feel it's my place to do so given you opened it.

**Comment by marcoms** [comment]
Sorry for the lack of input from me - I've been busy over the recent months. Does the Sublime Babel plugin help @DJTB?

**Comment by DJTB** [comment]
It greatly increases the tokenization and JSX becomes ugly as hell with lots of red :upside_down_face: 
So I had to tweak that back to the orange class color it was with normal vscode + oceanic.

Anyway, I was able to achieve a difference between key vs const vs string colors, which is what I wanted, by using Sublime Babel plugin and adding this override to settings :

```
"editor.tokenColorCustomizations": {
    "[Oceanic Plus]": {
      "textMateRules": [
        {
          "name": "Object Keys",
          "scope": "meta.group.braces.curly constant.other.object.key.js string.unquoted.label.js",
          "settings": {
            "foreground": "#e2e2e2"
          }
      ]
  }
}
```

![image](https://user-images.githubusercontent.com/5353151/37708715-cdf8b502-2d5b-11e8-92ba-78cfe01c5f04.png)
