### ISSUE TITLE
Would you consider adding a version with dimmed background?

### ISSUE THREAD

**Issue by algra** [marcoms/oceanic-plus#3]
Hi there,

A question: what's a font name you have on the screenshots?

And a suggestion: would you consider adding a version with a slightly dimmed background, like this theme got: https://github.com/voronianski/oceanic-next-color-scheme, it's #1d2225 instead of #1B2B34, I find it's a bit more comfortable. I can send you a pull request if you would merge it ;)

Thanks!

**Comment by marcoms** [comment]
I wouldn't mind having a darker variant but it would mean I'd have to maintain 2 separate versions of the theme, unless I'm missing something? Otherwise you could just use my theme and have a line in workbench.colorCustomizations which changes the background.

Font is Operator Mono
