### ISSUE TITLE
Color settings

### ISSUE THREAD

**Issue by junyicc** [marcoms/oceanic-plus#4]
Would you mind adding these settings into your default json so that users do not have to add these in their custom json.
```
"workbench.colorCustomizations": {
        "activityBarBadge.background": "#80CBC4",
        "list.activeSelectionForeground": "#80CBC4",
        "list.inactiveSelectionForeground": "#80CBC4",
        "list.highlightForeground": "#80CBC4",
        "scrollbarSlider.activeBackground": "#80CBC450",
        "editorSuggestWidget.highlightForeground": "#80CBC4",
        "textLink.foreground": "#80CBC4",
        "progressBar.background": "#80CBC4",
        "pickerGroup.foreground": "#80CBC4",
        "tab.activeBorder": "#80CBC4",
        "debugToolBar.background": "#16242C",
        "dropdown.background": "#16242C",
        "editorIndentGuide.activeBackground": "#80CBC450"
    },
```

**Comment by marcoms** [comment]
I've implemented a few of these with some tweaks. A few stood out to me:

>"activityBarBadge.background": "#80CBC4",

IMO it's a bit too bright to make it default, the contrast with the white text isn't a lot and would hurt accessibility, so I changed it to a darker variant.

>"list.activeSelectionForeground": "#80CBC4",
>"list.inactiveSelectionForeground": "#80CBC4",

Easy to get confused with git colors, so I left these out
